version: "2"
services:
  # Node 1
  node1:
    image: blockchain
    command: sh -c "yarn; nodemon --inspect=0.0.0.0:9229 index.js"
    volumes:
      - ".:/var/app"
    ports:
      - 6000:3000
    environment:
      DEBUG: "*"
      TERM: xterm-256color
      NODE_IP: node1
      NODE_PORT: 8080
      MONGO_URL: mongodb://node1_db:27017/blockchain
      MQTT_BROKER_IP: broker
      MQTT_BROKER_PORT: 1883
      DIFFICULTY: 2
    stdin_open: true
    tty: true
    container_name: "node1"

  # Node 2
  # node2:
  #   image: blockchain
  #   command: sh -c "yarn; nodemon index.js"
  #   volumes:
  #     - ".:/var/app"
  #   ports:
  #     - 3001:3000
  #   environment:
  #     DEBUG: "*"
  #     TERM: xterm-256color
  #     NODE_IP: node2
  #     NODE_PORT: 8081
  #     MONGO_URL: mongodb://node2_db:27017/blockchain
  #     MQTT_BROKER_IP: broker
  #     MQTT_BROKER_PORT: 1883
  #   stdin_open: true
  #   tty: true
  #   container_name: "node2"

  # Node 3
  # node3:
  #   image: blockchain
  #   command: sh -c "yarn; nodemon index.js"
  #   volumes:
  #     - ".:/var/app"
  #   ports:
  #     - 3002:3000
  #   environment:
  #     DEBUG: "*"
  #     TERM: xterm-256color
  #     NODE_IP: node3
  #     NODE_PORT: 8082
  #     MONGO_URL: mongodb://node3_db:27017/blockchain
  #     MQTT_BROKER_IP: broker
  #     MQTT_BROKER_PORT: 1883
  #   stdin_open: true
  #   tty: true
  #   container_name: "node3"

  broker:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
    stdin_open: true
    tty: true
    container_name: "broker"

networks:
  default:
    external:
      name: blockchain_webapp_default
