version: '2'
services:
  # Node 1
  node1:
    image: blockchain
    command: sh -c "yarn; nodemon index.js"
    volumes:
      - ".:/var/app"
    ports:
      - 3000:3000
      - 8080:8080
    environment:
      DEBUG: "*"
      TERM: xterm-256color
      NODE_PORT: 8080
    stdin_open: true
    tty: true
    container_name: "node1"
  # Node 2
  node2:
    image: blockchain
    command: sh -c "yarn; nodemon index.js"
    volumes:
      - ".:/var/app"
    ports:
      - 3001:3000
      - 8081:8080
    environment:
      DEBUG: "*"
      TERM: xterm-256color
      NODE_PORT: 8081
    stdin_open: true
    tty: true
    container_name: "node2"
  # Node 3
  node3:
    image: blockchain
    command: sh -c "yarn; nodemon index.js"
    volumes:
      - ".:/var/app"
    ports:
      - 3002:3000
      - 8082:8080
    environment:
      DEBUG: "*"
      TERM: xterm-256color
      NODE_PORT: 8082
    stdin_open: true
    tty: true
    container_name: "node3"