version: '2'
services:
  # Node 1
  node1:
    image: blockchain
    command: sh -c "yarn; nodemon index.js"
    volumes:
      - ".:/var/app"
    ports:
      - 3000:3000
      - 8080:8080
    environment:
      DEBUG: "*"
      TERM: xterm-256color
      NODE_PORT: 8080
      MONGO_URL: mongodb://node1_db:27017/blockchain
    stdin_open: true
    tty: true
    container_name: "node1"
    links:
      - node1_db
  node1_db:
    image: mongo:3.0.15
    container_name: "node1_db"

  # Node 2
  node2:
    image: blockchain
    command: sh -c "yarn; nodemon index.js"
    volumes:
      - ".:/var/app"
    ports:
      - 3001:3000
      - 8081:8080
    environment:
      DEBUG: "*"
      TERM: xterm-256color
      NODE_PORT: 8081
      MONGO_URL: mongodb://node2_db:27017/blockchain
    stdin_open: true
    tty: true
    container_name: "node2"
    links:
      - node2_db
  node2_db:
    image: mongo:3.0.15
    container_name: "node2_db"

  # Node 3
  node3:
    image: blockchain
    command: sh -c "yarn; nodemon index.js"
    volumes:
      - ".:/var/app"
    ports:
      - 3002:3000
      - 8082:8080
    environment:
      DEBUG: "*"
      TERM: xterm-256color
      NODE_PORT: 8082
      MONGO_URL: mongodb://node3_db:27017/blockchain
    stdin_open: true
    tty: true
    container_name: "node3"
    links:
      - node3_db
  node3_db:
    image: mongo:3.0.15
    container_name: "node3_db"