module.exports = {
  REQUEST_BLOCKCHAIN: "REQUEST_BLOCKCHAIN",
  BROADCAST_BLOCKCHAIN: "BROADCAST_BLOCKCHAIN",
  REQUEST_LATEST_BLOCK: "REQUEST_LATEST_BLOCK",
  RESPONSE_LATEST_BLOCK: "RESPONSE_LATEST_BLOCK",
  RESPONSE_NEW_BLOCK: "RESPONSE_NEW_BLOCK"
}
